// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tseksgdxfldgppzgfcwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZWtzZ2R4ZmxkZ3BwemdmY3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTMwMTcsImV4cCI6MjA1MzM2OTAxN30.QbWstnuq3TxTcozBu-CzGG9gsxis1REPvABopr0ahRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);